name: Build and Publish Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}  
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}-longest-substring:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}-longest-substring:latest


