name: Build and Publish Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - master  # This triggers the action on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional, but recommended for caching and better performance)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # Make sure we specify the correct registry
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate

      # Step 4: Build Docker image (ensure the name is lowercase)
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository | toLowerCase() }}/longest-substring:latest .

      # Step 5: Push Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository | toLowerCase() }}/longest-substring:latest

